version: '3.8'

services:
  redis:
    image: redis
    container_name: redis-queue
    ports:
      - "6379:6379"

  express:
    build: .
    container_name: express-app
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app
    command: npm run dev  # or `npm run start` depending on your setup
