version: '3.8'

services:
  redis:
    image: redis
    container_name: ticket-support-redis-queue
    ports:
      - "6379:6379"

  express:
    build: .
    container_name: ticket-support-express-app
    ports:
      - "5001:5001"
    env_file:
      - .env
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev  # or `npm run start` depending on your setup
